print ("This is the basic division with decimals calculator")
print ("Enter 2 numbers then see what the answer is")
print (" ")
print ("HOW THE PROGRAM WORKS")
print ("a and b are set as float commands. Float commands hold numbers with decimals. An input command is included")
print ("When you enter a number in A, it is stored in as an integer")
print ("When you enter a number in B, it is also stored in as an integer")
print ("The program then divides b from a with a print command")
print ("In python, the division sign is an front-slash / instead of an division symbol")
print ("So it looks like this")
print ("(a/b)")
print ("Instead of this")
print ("(a ÷ b)")
print ("Or with spacing")
print ("(a/b)")
print ("The answer is printed to your screen, then the program asks for input before it closes")
print ("Just press enter when that happens. You can type anything there, but it won't do anything")
print ("DO NOT USE ANY LETTERS OR THE PROGRAM WILL CRASH")
print (" ")
a = float(input("a="))
b = float(input("b="))
print ("Answer:")
print ("a / b =")
print ( a / b)
print (" ")
print ("Well done!")
input1 = input("Press enter to quit")