print ("This is the basic multiplication calculator")
print ("Enter 2 numbers (do not enter any decimals) then see what the answer is")
print (" ")
print ("HOW THE PROGRAM WORKS")
print ("a and b are set as integers. An input command is included")
print ("When you enter a number in A, it is stored in as an integer")
print ("When you enter a number in B, it is also stored in as an integer")
print ("The program then multiplies a and b with a print command")
print ("In python, the multiplication sign is an asterisk * instead of an x")
print ("So it looks like this")
print ("(a*b)")
print ("Instead of this")
print ("(a x b)")
print ("Or with spacing")
print ("(a*b)")
print ("The answer is printed to your screen, then the program asks for input before it closes")
print ("Just press enter when that happens. You can type anything there, but it won't do anything")
print ("DO NOT USE ANY LETTERS OR THE PROGRAM WILL CRASH")
print (" ")
a = int(input("a="))
b = int(input("b="))
print ("Answer:")
print ("a * b =")
print ( a * b)
print (" ")
print ("Well done!")
input1 = input("Press enter to quit")